### ISSUE TITLE
Tracking issue for initial release

### ISSUE THREAD

**Issue by wafflespeanut** [wafflespeanut/paperclip#14]
The following needs to be accomplished before we can go for an initial release.

- [x] Generate API objects from OpenAPI v2 schema
- [x] Generate builder structs for API objects and HTTP operations.
- [x] Add documentation for all builders and methods based on `description` field.
- [x] Add `Sendable` trait for API call and implement it for all fulfilled builders.
- [x] Add a global "pre request hook" for modifying `RequestBuilder` since we don't (currently) support any kind of auth.
- [x] Update README.
- [x] Add examples.
- [x] More tests! (including compiletests)
