### ISSUE TITLE
Parsing this openapi2 json file fails

### ISSUE THREAD

**Issue by TyPR124** [wafflespeanut/paperclip#99]
Stuff addressed by this issue:
- [x] Enums should be array of `any` rather than array of strings.
- [x] Objects can be defined in properties anonymously.
- [x] Objects can be defined in body parameters and responses in paths.

---

I have a swagger.json file which I'm trying to generate a client library from. Using swagger, it is able to generate a rust project but the project does not compile.

I am running `paperclip --api v2 -o unms-rs ./swagger.json` and get the error `error: Invalid value for '<spec>': JSON error: data did not match any variant of untagged enum SchemaRepr at line 1 column 126883`

The error location is immediately after a definition for "InterfaceOverview", though looking at it myself I don't see any obvious issue. I'm a bit new at this so I definitely could be missing something if there is an issue. The object is included at the bottom. I should also note that the file passes a validation test [here](https://mermade.org.uk/openapi-converter), although I haven't tried to validate it with anything else.

The file is linked below (with a .txt extension since apparently github doesn't accept .json extensions)

[swagger.txt](https://github.com/wafflespeanut/paperclip/files/3584180/swagger.txt)

Here is the InterfaceOverview object. The error location is the closing bracket of this object. (edit: I think I was off by one. The error location is the character immediately after the closing bracket)

```
"InterfaceOverview":{
	"type":"object",
	"description":"Read-only interface overview.",
	"properties":{
		"identification":{"$ref":"#/definitions/InterfaceIdentification"},
		"addresses":{"type":"array","items":{"$ref":"#/definitions/InterfaceAddressOverview"}},
		"status":{"type":"object","enum":[{"$ref":"#/definitions/InterfaceStatus"},null]},
		"statistics":{"$ref":"#/definitions/InterfaceStatistics"},
		"pppoe":{"type":"object","properties":{"id":{"$ref":"#/definitions/PPPOEID"}}},
		"vlan":{"type":"object","properties":{"id":{"type":"number"}}},
		"poe":{"$ref":"#/definitions/POE"},
		"enabled":{"type":"boolean","description":"Enable/Disable."},
		"visible":{"type":"boolean","description":"Logical switch which determines if it makes sense to display the interface to user."},
		"canDisplayStatistics":{"type":"boolean","description":"Logical switch which determines if it makes sense to display interface statistics to user."}
	}
}
```

**Comment by wafflespeanut** [comment]
The problem is in the `enum` field (in `status property). Enum support is still on its way, but failing to parse the JSON spec is indeed a bug. Thanks for filing! I'll take a look tomorrow :smile:

**Comment by wafflespeanut** [comment]
Oh, and the workaround would be to directly specify the `$ref` for that object. In the above example,

```json
"status": {
  "type": "object",
  "enum": [{
    "$ref": "#/definitions/InterfaceStatus"
  }, null]
},
```

... the `status` property is of type `object | null` and if it's an object, then it should conform to `InterfaceStatus` definition. But IIRC, all the properties of all definitions are nullable unless they're specified in `required` field in the schema. This means, we could change the above to:

```json
"status": {
  "type": "object",
  "$ref": "#/definitions/InterfaceStatus"
},
```

... and it should mean the same.

**Comment by TyPR124** [comment]
Thanks for the feedback. I'll do some testing this weekend to see if I can get something working with that workaround in the meantime.

**Comment by wafflespeanut** [comment]
I now have reason to suspect whether the above schema is even correct. A number of online references point to using `enum` for specifying "values", not schema. For example, this is correct:

```json
{
  "type": "string",
  "enum": ["A", "B", "C"]
}
```

... and so is this:

```json
{
  "type": "object",
  "properties": {
    "x": {
      "type": "string"
    },
    "y": {
      "type": "string"
    }
  },
  "enum": [{
    "x": "foo",
    "y": "bar"
  }, {
    "x": "boo",
    "y": "yaa"
  }]
}
```

In both cases, we're specifying allowed values for some type (`null` is also permitted), which is what enums are used for, so I'm not sure whether tools look at the `enum` field as an array of schemas since they're already looking at it as an array of values. On the other hand, the spec supports [`oneOf`](https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/), which does exactly this, so that's one other reason to suspect whether the above schema is correct.

For now, I'll fix the `enum` field in paperclip so that it accepts an array of `any` values, but I'm not planning to add schema support for enums until I find it in some spec.

**Comment by TyPR124** [comment]
> I now have reason to suspect whether the above schema is even correct.

I did a bit of searching but couldn't find anything definitive. I can only point to the fact that it works in swagger, but that doesn't necessarily mean it's *technically* correct.

I cleaned up a few instances of $ref inside an enum, but now I'm getting an error "Invalid name for definition" but no location info.

Is there maybe a list of definition names that are reserved?

[swagger_cleaned_enum_refs.txt](https://github.com/wafflespeanut/paperclip/files/3586681/swagger_cleaned_enum_refs.txt)

**Comment by wafflespeanut** [comment]
Thanks for taking a deeper look. Apparently, this is something I've overlooked when implementing schema resolution - I've accidentally gone under the false assumption that if an object has another object in one of its properties, then it's a reference. While that's usually the case, it doesn't conform with the spec, which does allow defining objects, even in properties.

OpenAPI objects relate to Rust structs, so sticking with references allows us to name the structs appropriately. Having an object definition in a property means that we still have to define the struct, but now we have to come up with a name for it.

In the above example, `lan` property is of type `object` whose Rust struct name is not known, but since we know the parent name (`AirCubeNetworkConfig`) and property name, I could just default to the struct name as `AirCubeNetworkConfigLan`. As more children come in, I could keep suffixing property names to the parent.

**Comment by TyPR124** [comment]
> I could just default to the struct name as AirCubeNetworkConfigLan

That seems reasonable to me. Maybe you're already dealing with this in another way, but I would think putting such types (with a generated names) in their own module (in this case, maybe something like `mod aircubenetworkconfig { struct AirCubeNetworkConfigLan { ... } }` might help in case of name conflicts.

**Comment by wafflespeanut** [comment]
Yep! Each API object already has its own module, because in addition to the structs, we also have their methods, builders and client impls for each operation.

**Comment by wafflespeanut** [comment]
I've fixed the enum problem and autogeneration of structs in definitions, but I've missed definitions in paths. I'll do that later.

**Comment by wafflespeanut** [comment]
The above commit fixes this bug. The CLI can successfully parse and resolve the file, but with some warnings, because a number of things required for the above spec file (#82, #83, #88, etc.) are still on their way.

**Comment by TyPR124** [comment]
Thank you. I can confirm that this is working now, at least as far as getting a lib that compiles.
